# Generated by Django 3.0.8 on 2020-11-01 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(default='', max_length=100)),
                ('repo_url', models.CharField(default='', max_length=300)),
                ('repo_desc', models.CharField(default='', max_length=300)),
                ('repo_languages', models.CharField(default='', max_length=50)),
                ('repo_createdat', models.CharField(default='', max_length=30)),
                ('repo_forks', models.IntegerField(default=0)),
                ('repo_size', models.IntegerField(default=0)),
                ('repo_stars', models.IntegerField(default=0)),
                ('repo_openissue', models.IntegerField(default=0)),
                ('repo_owner_url', models.CharField(default='', max_length=200)),
                ('repo_owner_img', models.CharField(default='', max_length=300)),
                ('repo_owner_name', models.CharField(default='', max_length=70)),
                ('repo_uploadedby_first_name', models.CharField(default='', max_length=30)),
                ('repo_uploadedby_last_name', models.CharField(default='', max_length=30)),
                ('repo_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
