# Generated by Django 3.0.8 on 2020-10-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepositories',
            name='Repository',
            field=models.CharField(default='users-name/repository-name', max_length=400),
        ),
    ]
