# Generated by Django 3.0.8 on 2020-10-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_githubrepositories_repository'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Repo_Name', models.CharField(max_length=100)),
                ('Repo_Url', models.CharField(max_length=300)),
                ('Repo_Desc', models.CharField(max_length=3000)),
                ('Repo_Language', models.CharField(max_length=50)),
                ('Repo_Createdat', models.IntegerField(max_length=10)),
                ('Repo_Forks', models.IntegerField(max_length=20)),
                ('Repo_Size', models.IntegerField(max_length=50)),
                ('Repo_Stars', models.IntegerField(max_length=50)),
                ('Repo_Owner_Url', models.CharField(max_length=200)),
                ('Repo_Owner_Img', models.CharField(max_length=300)),
                ('Repo_Owner_Name', models.CharField(max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='GithubRepositories',
        ),
    ]
