# Generated by Django 3.0.8 on 2020-10-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201031_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepository',
            name='Repo_Createdat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='Repo_Forks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='Repo_Size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='Repo_Stars',
            field=models.IntegerField(),
        ),
    ]
