# Generated by Django 3.0.8 on 2020-10-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20201031_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepository',
            name='Repo_OpenIssue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='Repo_Createdat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='Repo_Desc',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='Repo_Forks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='Repo_Size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='Repo_Stars',
            field=models.IntegerField(default=0),
        ),
    ]
