# Generated by Django 3.0.8 on 2020-10-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20201031_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepository',
            name='Repo_Createdat',
            field=models.CharField(max_length=30),
        ),
    ]
