# Generated by Django 3.0.8 on 2020-10-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Sno',
            new_name='Person_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='Email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='Message',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='contact',
            name='Name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
