# Generated by Django 3.0.8 on 2020-10-11 09:25

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='User_Profile',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=django.contrib.auth.models.User),
        ),
    ]
