# Generated by Django 3.0.8 on 2020-10-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201011_0925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Model',
        ),
    ]
